### ISSUE TITLE
"urllib3.exceptions.LocationValueError: No host specified" when starting the stack

### ISSUE THREAD

**Issue by gottoesplosivo** [arpanghosh8453/public-fitbit-projects#19]
Hi,

When starting my stack I get this error.
Any ideas on what I might have configured wrong?

```
fitbit-fetch-data  | 2024-07-21 14:16:31,128 - INFO - Attempting to refresh tokens...
fitbit-fetch-data  | 2024-07-21 14:16:31,128 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/oauth2/token
fitbit-fetch-data  | 2024-07-21 14:16:31,132 - DEBUG - Starting new HTTPS connection (1): api.fitbit.com:443
fitbit-fetch-data  | 2024-07-21 14:16:31,396 - DEBUG - https://api.fitbit.com:443 "POST /oauth2/token HTTP/1.1" 200 483
fitbit-fetch-data  | 2024-07-21 14:16:31,399 - INFO - Fitbit token refresh successful!
fitbit-fetch-data  | 2024-07-21 14:16:31,414 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/profile.json
fitbit-fetch-data  | 2024-07-21 14:16:31,703 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/heart/date/2024-07-20/1d/1sec.json
fitbit-fetch-data  | 2024-07-21 14:16:32,852 - INFO - Recorded HeartRate_Intraday intraday for date 2024-07-20
fitbit-fetch-data  | 2024-07-21 14:16:32,852 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/steps/date/2024-07-20/1d/1min.json
fitbit-fetch-data  | 2024-07-21 14:16:33,193 - INFO - Recorded Steps_Intraday intraday for date 2024-07-20
fitbit-fetch-data  | 2024-07-21 14:16:33,194 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/heart/date/2024-07-21/1d/1sec.json
fitbit-fetch-data  | 2024-07-21 14:16:34,114 - INFO - Recorded HeartRate_Intraday intraday for date 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:34,114 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/steps/date/2024-07-21/1d/1min.json
fitbit-fetch-data  | 2024-07-21 14:16:34,953 - INFO - Recorded Steps_Intraday intraday for date 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:34,953 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/hrv/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:35,468 - INFO - Recorded HRV for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:35,468 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/br/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:35,716 - INFO - Recorded BR for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:35,716 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/temp/skin/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:35,985 - INFO - Recorded Skin Temperature Variation for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:35,986 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/spo2/date/2024-07-20/2024-07-21/all.json
fitbit-fetch-data  | 2024-07-21 14:16:36,270 - INFO - Recorded SPO2 intraday for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:36,270 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1.2/user/-/sleep/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:36,609 - INFO - Recorded Sleep data for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:36,609 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/minutesSedentary/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:36,964 - INFO - Recorded minutesSedentaryfor date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:36,964 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/minutesLightlyActive/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:37,215 - INFO - Recorded minutesLightlyActivefor date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:37,215 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/minutesFairlyActive/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:37,470 - INFO - Recorded minutesFairlyActivefor date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:37,470 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/minutesVeryActive/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:37,731 - INFO - Recorded minutesVeryActivefor date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:37,731 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/distance/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:38,015 - INFO - Recorded distance for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:38,016 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/calories/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:38,286 - INFO - Recorded calories for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:38,286 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/tracker/steps/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:38,540 - INFO - Recorded Total Steps for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:38,541 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/heart/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:38,918 - INFO - Recorded RHR and HR zones for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:38,918 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/spo2/date/2024-07-20/2024-07-21.json
fitbit-fetch-data  | 2024-07-21 14:16:39,410 - INFO - Recorded Avg SPO2 for date 2024-07-20 to 2024-07-21
fitbit-fetch-data  | 2024-07-21 14:16:39,411 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/devices.json
fitbit-fetch-data  | 2024-07-21 14:16:39,684 - INFO - Recorded battery level for Charge6
fitbit-fetch-data  | 2024-07-21 14:16:39,684 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/list.json
fitbit-fetch-data  | 2024-07-21 14:16:44,584 - INFO - Fetched 50 recent activities before date 2024-07-21
fitbit-fetch-data  | Traceback (most recent call last):
fitbit-fetch-data  |   File "/app/Fitbit_Fetch.py", line 585, in <module>
fitbit-fetch-data  |     write_points_to_influxdb(collected_records)
fitbit-fetch-data  |   File "/app/Fitbit_Fetch.py", line 190, in write_points_to_influxdb
fitbit-fetch-data  |     influxdb_write_api.write(bucket=INFLUXDB_BUCKET, org=INFLUXDB_ORG, record=points)
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/client/write_api.py", line 378, in write
fitbit-fetch-data  |     results = list(map(write_payload, payloads.items()))
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/client/write_api.py", line 376, in write_payload
fitbit-fetch-data  |     return self._post_write(_async_req, bucket, org, final_string, payload[0])
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/client/write_api.py", line 509, in _post_write
fitbit-fetch-data  |     return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
fitbit-fetch-data  |     (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
fitbit-fetch-data  |     return self.api_client.call_api(
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
fitbit-fetch-data  |     return self.__call_api(resource_path, method,
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
fitbit-fetch-data  |     response_data = self.request(
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
fitbit-fetch-data  |     return self.rest_client.POST(url,
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
fitbit-fetch-data  |     return self.request("POST", url,
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 220, in request
fitbit-fetch-data  |     r = self.pool_manager.request(
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/urllib3/_request_methods.py", line 144, in request
fitbit-fetch-data  |     return self.request_encode_body(
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
fitbit-fetch-data  |     return self.urlopen(method, url, **extra_kw)
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 433, in urlopen
fitbit-fetch-data  |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
fitbit-fetch-data  |   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 295, in connection_from_host
fitbit-fetch-data  |     raise LocationValueError("No host specified.")
fitbit-fetch-data  | urllib3.exceptions.LocationValueError: No host specified.
fitbit-fetch-data exited with code 1
```

**Comment by arpanghosh8453** [comment]
May I see your docker compose with environment variables?

**Comment by gottoesplosivo** [comment]
> May I see your docker compose with environment variables?

I actually double checked my docker compose and realised I mispelled a couple of variables.
It's working now :)
