### ISSUE TITLE
Potential Bug? KeyError: 'activities-heart-intraday'

### ISSUE THREAD

**Issue by Jasonthefirst** [arpanghosh8453/public-fitbit-projects#23]
I run the app in Docker. The connection to Fitbit worked (I think). But it won't fetch data but report the following error:

```
docker pull thisisarpanghosh/fitbit-fetch-data:latest && docker compose run --rm fitbit-fetch-data
latest: Pulling from thisisarpanghosh/fitbit-fetch-data
Digest: sha256:67afde23284b5287cb1b86de08f2a03ebb8f6b9edde71247e518db291d1f4b89
Status: Image is up to date for thisisarpanghosh/fitbit-fetch-data:latest
docker.io/thisisarpanghosh/fitbit-fetch-data:latest
2024-10-25 09:35:19,867 - INFO - Attempting to refresh tokens...
2024-10-25 09:35:19,867 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/oauth2/token
2024-10-25 09:35:19,871 - DEBUG - Starting new HTTPS connection (1): api.fitbit.com:443
2024-10-25 09:35:20,179 - DEBUG - https://api.fitbit.com:443 "POST /oauth2/token HTTP/11" 200 None
2024-10-25 09:35:20,180 - INFO - Fitbit token refresh successful!
2024-10-25 09:35:20,180 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/profile.json
2024-10-25 09:35:20,181 - DEBUG - Starting new HTTPS connection (1): api.fitbit.com:443
2024-10-25 09:35:20,530 - DEBUG - https://api.fitbit.com:443 "GET /1/user/-/profile.json HTTP/11" 200 None
2024-10-25 09:35:20,541 - DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/heart/date/2024-10-24/1d/1sec.json
2024-10-25 09:35:20,542 - DEBUG - Starting new HTTPS connection (1): api.fitbit.com:443
2024-10-25 09:35:20,900 - DEBUG - https://api.fitbit.com:443 "GET /1/user/-/activities/heart/date/2024-10-24/1d/1sec.json HTTP/11" 200 None
Traceback (most recent call last):
  File "/app/Fitbit_Fetch.py", line 578, in <module>
    get_intraday_data_limit_1d(date_str, [('heart','HeartRate_Intraday','1sec'),('steps','Steps_Intraday','1min')]) # 2 queries x number of dates ( default 2)
  File "/app/Fitbit_Fetch.py", line 261, in get_intraday_data_limit_1d
    data = request_data_from_fitbit('https://api.fitbit.com/1/user/-/activities/' + measurement[0] + '/date/' + date_str + '/1d/' + measurement[2] + '.json')["activities-" + measurement[0] + "-intraday"]['dataset']
KeyError: 'activities-heart-intraday'

```

Is this an error on my end and I do have to change something or did fitbit change something with their API?

Thank you for your work.

**Comment by arpanghosh8453** [comment]
@Jasonthefirst Please look into #7 

It looks like your application on Fitbit (from where you obtained the API keys) is server or client type. Please make it to personal if you want to access intraday data. 

If you read the [readme](https://github.com/arpanghosh8453/public-fitbit-projects?tab=readme-ov-file#how-to-setup-the-script) that also mentions the following 

`❗❗ The Fitbit application must be personal type for the access of intraday data series ❗❗`

Let me know if that change fixes your issue. Thank you and happy to help :)

**Comment by arpanghosh8453** [comment]
There are no stupid questions, and I appreciate you reaching out. Thank you for using my project! If you like it, please consider giving it a star :)

Have a good day!
