### ISSUE TITLE
Get_New_Access_Token - Error

### ISSUE THREAD

**Issue by rantanlan** [arpanghosh8453/public-fitbit-projects#25]
I was happily running your container for some month now, but it just stopped working. Looks like it couldn't renew the access token?
It throws  the following error:

```
docker pull thisisarpanghosh/fitbit-fetch-data:latest && docker compose run --rm fitbit-fetch-data
latest: Pulling from thisisarpanghosh/fitbit-fetch-data
Digest: sha256:4a1ec949eef42b667b9601e37e2afe4b7a2c7c32d761600650f8c931144905aa
Status: Image is up to date for thisisarpanghosh/fitbit-fetch-data:latest
docker.io/thisisarpanghosh/fitbit-fetch-data:latest
Traceback (most recent call last):
  File "/app/Fitbit_Fetch.py", line 163, in <module>
    ACCESS_TOKEN = Get_New_Access_Token(client_id, client_secret)
  File "/app/Fitbit_Fetch.py", line 157, in Get_New_Access_Token
    access_token, refresh_token = load_tokens_from_file()
  File "/app/Fitbit_Fetch.py", line 152, in load_tokens_from_file
    tokens = json.load(file)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm using the latest image with this compose:

```
services:
  fitbit-fetch-data:
    image: thisisarpanghosh/fitbit-fetch-data:latest
    container_name: fitbit-fetch-data
    restart: unless-stopped
    volumes:
      - /srv/fitbit_dashboard/logs:/app/logs # logs folder should exist and owned by user id 1000
      - /srv/fitbit_dashboard/tokens:/app/tokens # tokens folder should exist and owned by user id 1000
      - /etc/timezone:/etc/timezone:ro
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/fitbit.token
      - OVERWRITE_LOG_FILE=True
      - INFLUXDB_VERSION=1 # supported values are 1 and 2 
      - INFLUXDB_BUCKET=your_bucket_name_here # for influxdb 2.x
      - INFLUXDB_ORG=your_org_here # for influxdb 2.x
      - INFLUXDB_TOKEN=your_token_here # for influxdb 2.x
      - INFLUXDB_URL=your_influxdb_server_location_with_port_here # for influxdb 2.x
      - INFLUXDB_HOST=influxdb # for influxdb 1.x
      - INFLUXDB_PORT=8086 # for influxdb 1.x
      - INFLUXDB_USERNAME=fitbit_user # for influxdb 1.x
      - INFLUXDB_PASSWORD=fitbit_password # for influxdb 1.x
      - INFLUXDB_DATABASE=fitbit_database # for influxdb 1.x
      - CLIENT_ID=XXX # Change this to your client ID
      - CLIENT_SECRET=XXX # Change this to your client Secret
      - DEVICENAME=PixelWatch2 # Change this to your device name - e.g. "Charge5"
      - LOCAL_TIMEZONE=Automatic # set to "Automatic" for Automatic setup from User profile (if not mentioned here specifically). 
    networks:
      - fitbit_dashboard
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=fitbit_database
      - INFLUXDB_USER=fitbit_user
      - INFLUXDB_USER_PASSWORD=fitbit_password
    ports:
      - 8086:8086
    volumes:
      - /srv/fitbit_dashboard/influxdb:/var/lib/influxdb
    networks:
      - fitbit_dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - /srv/fitbit_dashboard/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - fitbit_dashboard
      - services
networks:
  fitbit_dashboard: {}
  services:
    external: true
```

I tried to register a new application, like i did the first. But the error is the same with the new ID and Secret.

Do you have any hint where I could take a look? The fitbit.token file is empty ... Thanks!

**Comment by arpanghosh8453** [comment]
> The fitbit.token file is empty

Hi @rantanlan, I think the problem is the contents of the file is wiped whereas the file is still present, so that is why it's not going back to registration mode. 

Please follow the instructions to get a new refresh token (which is valid now) from the fitbit applications website. Stop and remove the running instances of the container. Make sure in the mapped path `/srv/fitbit_dashboard/tokens`, the `fitbit.token` file is not present (remove the empty file you have from the folder). Then try `docker compose run --rm fitbit-fetch-data` to initialize the process, it should ask you for the refresh token like it did the first time. Once that is set up, you can stop that container and run it in regular mode by `docker compose up` in the folder containing the docker compose file. 

Let me know if that helps. Thank you.

**Comment by rantanlan** [comment]
Thanks, just deleting the fitbit.token did the job (should have tried that before reporting, sorry.) Thanks!

**Comment by arpanghosh8453** [comment]
@rantanlan No worries, Thank you for reaching out to me! I am happy to help. I knew just deleting the file would be enough, but just wanted to give a comprehensive guide to ensure it works for you. 

Have a good one and enjoy your daily/yearly stats from your Fitbit without a subscription fee!
