### ISSUE TITLE
Error retrieving data during intialization

### ISSUE THREAD

**Issue by badi95** [arpanghosh8453/public-fitbit-projects#4]
During first run of `docker-compose run publicfitbitprojects` after entering refresh token getting error:
``` Traceback (most recent call last):
  File "/app/Fitbit_Fetch.py", line 542, in <module>
    get_intraday_data_limit_1d(date_str, [('heart','HeartRate_Intraday','1sec'),('steps','Steps_Intraday','1min')]) # 2 queries x number of dates ( default 2)
  File "/app/Fitbit_Fetch.py", line 216, in get_intraday_data_limit_1d
    data = request_data_from_fitbit('https://api.fitbit.com/1/user/-/activities/' + measurement[0] + '/date/' + date_str + '/1d/' + measurement[2] + '.json')["activities-" + measurement[0] + "-intraday"]['dataset']
KeyError: 'activities-heart-intraday'```

**Comment by arpanghosh8453** [comment]
If Intraday data is not supported by your device, please comment out the following lines containing get_intraday_data_limit_1d ( ) function:

https://imgur.com/njNRz5R

line no 542, 586, 599 in the Fitbit_Fetch.py file to be specific.

**Comment by badi95** [comment]
That got me further along once I commented out the for loops on 541 and 585.

Now I'm getting an error:
```Fitbit API request failed. Status code: 403 API client is not authorized by Fitbit to access the resource requested. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.
Traceback (most recent call last):
  File "/app/Fitbit_Fetch.py", line 543, in <module>
    get_daily_data_limit_30d(start_date_str, end_date_str) # 3 queries
  File "/app/Fitbit_Fetch.py", line 296, in get_daily_data_limit_30d
    spo2_data_list = request_data_from_fitbit('https://api.fitbit.com/1/user/-/spo2/date/' + start_date_str + '/' + end_date_str + '/all.json')
  File "/app/Fitbit_Fetch.py", line 100, in request_data_from_fitbit
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.fitbit.com/1/user/-/spo2/date/2023-08-27/2023-08-28/all.json```

Maybe doesn't like trying to get 8/28 data when it's still 8/27?

**Comment by arpanghosh8453** [comment]
Yes, your spo2 for that date is not updated yet and hence you get that error.
